# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

# get_todays_date:
#   description: Retrieve the current date with timestamp and timezone.
#   type: function
#   function_name: get_todays_date

location_suggesting_task:
  description: >
    Suggest a list of potential event locations based on the given criteria.
    The criteria may include factors such as capacity, location, amenities, and budget.
  expected_output: >
    A list of 5 potential event locations that meet the given criteria, with a brief description of each location.
  agent: location_suggesting_agent
